subs:
  ros__parameters:
    # cam_topics: ['right_camera/image', 'left_camera/image']
    cam_topics: ['right_camera/image']
    bbox_topics: ['right_set/bbox']
    model_path: '/home/chengjing/Desktop/multi_cam_detection/src/multi_cam_obj_detection/multi_cam_obj_detection/yolov5s.pt'
    hub_cfg: '/home/chengjing/Desktop/multi_cam_detection/src/multi_cam_obj_detection/multi_cam_obj_detection/'
    model_conf: 0.5
    model_iou: 0.45
    queue_size : 5
    slop: 0.1